[[news]]
date = "2025-12"
content = "ðŸš€ Joined the School of Mechanical and Aerospace Engineering (MAE) at NTU as a Postdoctoral Fellow, advised by Prof. Mir."

[[news]]
date = "2024-11"
content = "âš¡ Joined the School of Electrical and Electronic Engineering (EEE) at NTU as a Postdoctoral Fellow, supervised by Prof. Lihua Xie."

[[news]]
date = "2024-09"
content = "ðŸŽ“ Received my Ph.D. degree from Harbin Institute of Technology (HIT)."
